from pydantic import BaseModel
from typing import List, Optional
import datetime

class Item(BaseModel):
    apparel: str
    size: str
    color: str
    img_id: str
    prompt: str
    price: float
    toggled: str
    thumbnail: Optional[str] = None
    img_url: Optional[str] = None

class OrderItem_new(BaseModel):
    user_id: str
    order_id: str
    item: List[Item]
    shipping_info: dict
    status: str
    org_id: str
    org_name: str
    autogenerated: bool
    timestamp: datetime.datetime
